[package]
name = "kurenai"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.5"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
rand = { version = "0.10.2", features = ["std", "sys_rng", "chacha"] }
sha3 = "0.10.8"
zeroize = "1.8.2"
zeroize_derive = "1.4.3"
chrono = "0.4.44"
chrono-tz = "0.10.4"
